[profile.dev]
opt-level = 1

[package]
name = "gpu-fluid-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
winit = "0.30.12"
gpu-allocator = "0.28.0"
glam = { version = "0.30.9", features = ["bytemuck"] }
rand = "0.9.2"
bytemuck = { version = "1.24.0", features = ["derive", "min_const_generics"] }
anyhow = "1.0.104"
clap = { version = "4.6.1", default-features = false, features = ["std", "help", "usage", "error-context"] }

[dev-dependencies]
criterion = "0.8.2"

[build-dependencies]
ureq = "2.9"      # A lightweight, synchronous HTTP client
flate2 = "1.0"    # To decompress .tar.gz (Linux/macOS)
tar = "0.4"       # To unpack .tar archives (Linux/macOS)

[[bench]]
name = "gpu_bench_main" 
harness = false
